backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/images/blog"
public_folder: "../../assets/images/blog"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titulok", name: "title", widget: "string"}
      - {label: "Dátum", name: "date", widget: "datetime"}
      - {label: "Autor", name: "author", widget: "string", default: "Peter"}
      - {label: "Hlavný Obrázok", name: "image", widget: "image"}
      - {label: "Tagy", name: "tags", widget: "list", default: ["Trendy"]}
      - {label: "Krátky popis", name: "excerpt", widget: "text"}
      - {label: "Obsah", name: "body", widget: "markdown"}